const arrayValueProductTitle = [
  { value: "Almond", label: "Almond" },
  { value: "Apple", label: "Apple" },
  { value: "Apricot", label: "Apricot" },
  { value: "Banana", label: "Banana" },
  { value: "Cabbage", label: "Cabbage" },
  { value: "Cherry", label: "Cherry" },
  { value: "Corn", label: "Corn" },
  { value: "Cucumber", label: "Cucumber" },
  { value: "Lemon", label: "Lemon" },
  { value: "Melon", label: "Melon" },
  { value: "Onion", label: "Onion" },
  { value: "Parsley", label: "Parsley" },
  { value: "Peach", label: "Peach" },
  { value: "Persimmon", label: "Persimmon" },
  { value: "Plum", label: "Plum" },
  { value: "Potato", label: "Potato" },
  { value: "Rice", label: "Rice" },
  { value: "Tomato", label: "Tomato" },
  { value: "Watermelon", label: "Watermelon" },
  { value: "Walnut", label: "Walnut" },
  { value: "Wheat", label: "Wheat" },
  { value: "Other", label: "Other" },
];
export default arrayValueProductTitle;
