import { StyleSheet } from "react-native";
import color from "../../constants/colorStyle";

export default StyleSheet.create({
  mainContainer: {
    display: "flex",
    flexDirection: "row",
    minHeight: 120,
  },
  image: {
    width: 120,
    height: 120,
    marginRight: 16,
  },
  informationContainer: {
    flex: 1,
  },
  informationPriceAndBatContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: 4,
  },
  betContainer: {
    display: "flex",
    flexDirection: "column",
  },
  priceContainer: {
    display: "flex",
    flexDirection: "column",
  },
  cont: {
    display: "flex",
    justifyContent: "flex-end",
  },
  secCont: {
    display: "flex",
    justifyContent: "flex-end",
    minHeight: 24,
  },
  informationTitle: {
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.15,
    color: "#131314",
    marginRight: 10,
    fontFamily: "IBMPlexSans-Regular",
  },
  informationTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
  },
  informationLocation: {
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.2,
    color: "#798787",
    fontFamily: "IBMPlexSans-Medium",
  },
  informationPostDateTime: {
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.2,
    color: "#798787",
    marginBottom: 16,
  },
  dataCreateWrap: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginBottom: 16,
    marginTop: 4,
  },
  noBets: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.15,
    color: "#BCC3C3",
    fontFamily: "IBMPlexSans-Regular",
  },
  betContainer: {
    display: "flex",
    flexDirection: "column",
    marginRight: 4,
    width: "50%",
  },
  bet: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.15,
    marginBottom: 4,
    fontFamily: "IBMPlexSans-Regular",
  },
  myBet: {
    color: color.myBet,
  },
  anotherBet: {
    color: color.anotherBet,
  },
  betTimeContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 4,
    paddingVertical: 8,
    backgroundColor: "#F87E25",
    borderRadius: 4,
    width: 75,
  },
  betTime: {
    color: "white",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.2,
  },
  Icon: {
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 10,
    marginRight: 5.5,
  },
  price: {
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.15,
    color: "#131314",
    marginBottom: 4,
  },
  priceContainer: {
    display: "flex",
    flexDirection: "column",
    marginRight: "auto",
    marginLeft: 0,
    width: "50%",
  },
  id: {
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.2,
    color: "#798787",
    fontFamily: "IBMPlexSans-Regular",
    marginLeft: 6,
  },
});
