import { StyleSheet } from "react-native";
import color from "../../constants/colorStyle";

export default StyleSheet.create({
  container: {
    display: "flex",
    flexDirection: "column",
  },
  image: {
    height: 160,
    marginBottom: 16,
  },
  section: {
    width: "50%",
  },
  title: {
    fontFamily: "IBMPlexSans-Regular",
    color: "#131314",
    fontWeight: "500",
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: 0.15,
    marginBottom: 8,
  },
  rejected: {
    backgroundColor: "#FDECE9",
    height: 24,
    width: 83,
    borderColor: "#D72C00",
    borderRadius: 20,
    borderStyle: "solid",
    borderWidth: 1,
    marginLeft: 8,
  },
  rejectedText: {
    fontFamily: "IBMPlexSans-Regular",
    color: "#EB3D26",
    paddingVertical: 1,
    paddingHorizontal: 11,
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.15,
  },
  moderation: {
    backgroundColor: "#EEF7FF",
    height: 24,
    width: 122,
    borderColor: "#368ACE",
    borderRadius: 20,
    borderStyle: "solid",
    borderWidth: 1,
    marginLeft: 8,
  },
  moderationText: {
    fontFamily: "IBMPlexSans-Regular",
    color: "#368ACE",
    paddingVertical: 1,
    paddingHorizontal: 11,
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.15,
  },
  modComment: {
    backgroundColor: "#FDECE9",
    height: 64,
    width: "100%",
    borderColor: "#D72C00",
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    paddingLeft: 22,
    justifyContent: "center",
  },
  wrapComment: {
    flexDirection: "row",
  },
  modCommentText: {
    fontFamily: "IBMPlexSans-Regular",
    paddingLeft: 14,
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.15,
  },
  wrapTimer: {
    marginBottom: 8,
    flexDirection: "row",
  },
  subtitles: {
    fontFamily: "IBMPlexSans-Regular",
    color: "#798787",
    fontWeight: "400",
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.2,
    marginTop: 4,
  },
  textContainer: {
    display: "flex",
    flexDirection: "row",
    paddingVertical: 16,
    width: "100%",
  },
  sectionTitle: {
    fontFamily: "IBMPlexSans-Regular",
    color: "#798787",
    fontWeight: "300",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.2,
  },
  bet: {
    fontFamily: "IBMPlexSans-Regular",
    fontWeight: "500",
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: 0.15,
    marginBottom: 4,
    color: "#12AB74",
  },
  noBet: {
    fontFamily: "IBMPlexSans-Regular",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.15,
    marginBottom: 4,
    color: "#BCC3C3",
  },
  price: {
    fontFamily: "IBMPlexSans-Regular",
    color: "#131314",
    fontWeight: "500",
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: 0.15,
    marginBottom: 4,
  },
  sectionWeight: {
    fontFamily: "IBMPlexSans-Regular",
    color: color.grey,
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.2,
  },
  id: {
    fontFamily: "IBMPlexSans-Regular",
    color: color.grey,
    fontWeight: "400",
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.2,
    margin: 4,
  },
  dataCreate: {
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.2,
    color: color.colorText,
    marginVertical: 5,
    marginRight: 20,
  },
  icon: {
    fontFamily: "IBMPlexSans-Regular",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 10,
    marginRight: 5.5,
  },
  priceTimeContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 4,
    paddingVertical: 8,
    backgroundColor: "#EEF7FF",
    borderRadius: 4,
    width: 75,
    marginTop: 8,
  },
  priceTime: {
    fontFamily: "IBMPlexSans-Regular",
    color: "#2978B8",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.2,
  },
  buttonContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 4,
  },
  buttonTextGreen: {
    fontFamily: "IBMPlexSans-Regular",
    color: "#38999B",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.3,
    marginLeft: 11,
  },
  buttonTextWhite: {
    fontFamily: "IBMPlexSans-Regular",
    color: "white",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.3,
    marginLeft: 11,
  },
  imageFaded: {
    height: 160,
    marginBottom: 8,
    opacity: 0.3,
  },
});
